//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoBikeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Details
    {
        public int export_detail_id { get; set; }
        public int export_id { get; set; }
        public int vehicle_id { get; set; }
        public decimal price { get; set; }
    
        public virtual Export_Stock Export_Stock { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
