//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoBikeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Export_Stock()
        {
            this.Export_Details = new HashSet<Export_Details>();
        }
    
        public int export_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> export_date { get; set; }
        public string reason { get; set; }
        public string receiver { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Export_Details> Export_Details { get; set; }
        public virtual User User { get; set; }
    }
}
