//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoBikeManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Brand
    {
        public int id { get; set; }
        public int supplier_id { get; set; }
        public string brand { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
